version: '3.9'

services:
  app:
    build:
      context: .
    depends_on:
      - "mysqldb"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_PORT=3306
      - MYSQL_HOST=mysqldb
    command: >
      bash -c "pytest -vv
      && jupyter lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token=''"
    ports:
      - 8888:8888
    volumes:
      - ./:/app
  mysqldb:
    image: mysql:8.0.29
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
