version: '3.9'

services:
  app:
    build:
      context: .
    depends_on:
      - "mysqldb"
    volumes:
      - ./:/app
    command: ["pytest",  "-v"]
  mysqldb:
    image: mysql:8.0.29
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
